var pkg = require('./package.json');

var src = 'app',
	dist = 'build',
	qlik = '/resources';

module.exports = {
	src: src,
	dist: dist,
	tmp: src + '/.tmp',
	server: {
		dev: 'http://localhost:4848', // Used for Qlik Sense Desktop
		prod: 'https://usnyc-dcp2.qliktech.com' // For NPM module to fill in
	},
	sass: {
		main: 'app.scss',
		files: '**/*.{sass,scss}',
		settings: {
			style: 'expanded'
		}
	},
	css: {
		files: '**/*.css',
		main: 'app.css',
		minName: 'app.min.css',
		autoprefixer: [
			'last 2 versions',
			'ie8',
			'ie9'
		]
	},
	js: {
		files: '**/{*,*.*}.js',
		ngFiles: '**/*.*.js',
		minName: 'app.min.js',
		jshint: '.jshintrc'
	},
	html: {
		files: '**/{*,*.*}.html',
		main: 'index.html',
		templates: 'app.templates.js'
	},
	bower: {
		src: 'vendor',
		minName: 'vendor.min.js'
	},
	qlik: {
		startTag: '<!-- inject:qlik -->',
		files: [
			qlik + '/autogenerated/qlikui.css',
			qlik + '/assets/client/client.css',
			qlik + '/assets/external/requirejs/require.js'
		],
		copyFiles: [
			'wbfolder.wbl',
			'QSTemplate.qext'
		]
	},
	wirdep: {
		exclude: ['vendor/moment/moment.js']
	},
	zip: 'QSTemplate.zip'
};